name: smart-sdk-manager
services:
  smart-sdk:
    container_name: smart-sdk
    image: smart/sdk:v0.0.1
    build:
      context: ..
      dockerfile: deployment/web/Dockerfile
    ports:
      - "8173:8173"
    networks:
      - smart-sdk
    volumes:
      - ../:/app
    tty: true
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
  server-sdk:
    container_name: server-sdk
    image: smart/sdk/server:v0.0.1
    build:
      context: ..
      dockerfile: deployment/server/Dockerfile
    ports:
      - "6173:6173"
    networks:
      - smart-sdk
    tty: true
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
networks:
  smart-sdk:
    name: smart-sdk
    driver: bridge
